//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainProgram.Assets.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 3D 立体地图 的本地化字符串。
        /// </summary>
        internal static string GroupLayer3DMap {
            get {
                return ResourceManager.GetString("GroupLayer3DMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D 平面地图 的本地化字符串。
        /// </summary>
        internal static string GroupLayer3DPlaneMap {
            get {
                return ResourceManager.GetString("GroupLayer3DPlaneMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D 路径 的本地化字符串。
        /// </summary>
        internal static string GroupLayer3DRoute {
            get {
                return ResourceManager.GetString("GroupLayer3DRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径分析 的本地化字符串。
        /// </summary>
        internal static string GroupLayer3DRouteAnalysis {
            get {
                return ResourceManager.GetString("GroupLayer3DRouteAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MapData2D 的本地化字符串。
        /// </summary>
        internal static string MapDataset2DName {
            get {
                return ResourceManager.GetString("MapDataset2DName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MapData3D 的本地化字符串。
        /// </summary>
        internal static string MapDataset3DName {
            get {
                return ResourceManager.GetString("MapDataset3DName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Route_ND 的本地化字符串。
        /// </summary>
        internal static string NetWorkDatasetName {
            get {
                return ResourceManager.GetString("NetWorkDatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Barries 的本地化字符串。
        /// </summary>
        internal static string PointBarriesFeatureClassName {
            get {
                return ResourceManager.GetString("PointBarriesFeatureClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResultRoute 的本地化字符串。
        /// </summary>
        internal static string ResultRouteLayerName {
            get {
                return ResourceManager.GetString("ResultRouteLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径分析 的本地化字符串。
        /// </summary>
        internal static string RouteAnalysisGroupLayerName {
            get {
                return ResourceManager.GetString("RouteAnalysisGroupLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stops 的本地化字符串。
        /// </summary>
        internal static string StopsFeatureClassName {
            get {
                return ResourceManager.GetString("StopsFeatureClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stops 的本地化字符串。
        /// </summary>
        internal static string StopsLayerName {
            get {
                return ResourceManager.GetString("StopsLayerName", resourceCulture);
            }
        }
    }
}
